name: "Delete Subdomain"

on:
  issues:
    types: [opened]

jobs:
  Register:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'Delete'
    permissions:
      issues: write
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1
      
    - name: Edit Subdomain
      env:
        EVENT_ISSUE_BODY: ${{ github.event.issue.body }}
        EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
            npm i cloudflare
            node --no-deprecation delete > data.csv
            cat data.csv
            comment=$(cut -d "|" -f 2 data.csv)
            reason=$(cut -d "|" -f 1 data.csv)
            gh issue edit https://github.com/is-probably-gay/is-probably-gay/issues/${{ github.event.issue.number }} --add-label "domain delete"
            gh issue close https://github.com/is-probably-gay/is-probably-gay/issues/${{ github.event.issue.number }} --comment "$comment" --reason "$reason"
            if [ "$reason" = "completed" ]
            then
              gh issue edit https://github.com/is-probably-gay/is-probably-gay/issues/${{ github.event.issue.number }} --add-label "success"
            else
              gh issue edit https://github.com/is-probably-gay/is-probably-gay/issues/${{ github.event.issue.number }} --add-label "failed"
            fi
